name: Update README with Today's Commits
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
permissions:
  contents: write  # Grants permission to write to repository contents
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Today's Commits
        run: |
          TODAY_COMMITS=$(git rev-list --count --author="Faturrachman-dev" --since="1.day" origin/main || echo "0")
          echo "TODAY_COMMITS=$TODAY_COMMITS" >> $GITHUB_ENV
      - name: Update README
        run: |
          if grep -q "<!-- TODAY_COMMITS -->" README.md; then
            sed -i "s|\(https://img.shields.io/badge/Today's%20Commits-.*-blue\)|\1${{ env.TODAY_COMMITS }}-blue|g" README.md
          else
            echo "![Today's Commits](https://img.shields.io/badge/Today's%20Commits-${{ env.TODAY_COMMITS }}-blue)" >> README.md
          fi
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update today's commits"
