name: Update README with Today's Commits
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: Faturrachman-dev/faturrachman-dev
          path: faturrachman-dev

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get Today's Commits Across All Repositories
        env:
          COMMIT_COUNTER_TOKEN: ${{ secrets.COMMIT_COUNTER_TOKEN }}
        run: |
          # Calculate the start of the current day in WIB (UTC+7)
          TODAY_START=$(TZ=Asia/Jakarta date +%Y-%m-%d)
          TODAY_START_UTC=$(date -u -d "$TODAY_START 00:00:00 -7 hours" +%Y-%m-%dT%H:%M:%SZ)
          echo "Counting commits since: $TODAY_START_UTC (00:00 WIB)"

          # Get the list of repositories for the user with pagination
          PAGE=1
          REPOS=""
          RETRY_COUNT=0
          while true; do
            RESPONSE=$(curl -s -D headers.txt -H "Authorization: Bearer $COMMIT_COUNTER_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/users/Faturrachman-dev/repos?per_page=100&page=$PAGE")
            if [[ $? -ne 0 ]]; then
              RETRY_COUNT=$((RETRY_COUNT + 1))
              if [[ $RETRY_COUNT -gt 3 ]]; then
                echo "Error: Failed to fetch repositories after 3 retries"
                exit 1
              fi
              echo "Retrying repository list fetch ($RETRY_COUNT/3)..."
              sleep 5
              continue
            fi
            NEW_REPOS=$(echo "$RESPONSE" | jq -r '.[].name' | tr '\n' ' ')
            REPOS="$REPOS $NEW_REPOS"
            LINK=$(grep -i '^link:' headers.txt || true)
            rm headers.txt
            if [[ ! "$LINK" =~ "rel=\"next\"" ]]; then
              break
            fi
            PAGE=$((PAGE + 1))
            sleep 2  # Increased sleep for stability
          done
          
          TOTAL_COMMITS=0
          
          # Loop through each repository and count commits
          for REPO in $REPOS; do
            echo "Processing repository: $REPO"
            
            # Count commits with pagination
            COMMITS=0
            PAGE=1
            RETRY_COUNT=0
            while true; do
              curl -s -D headers.txt -H "Authorization: Bearer $COMMIT_COUNTER_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/Faturrachman-dev/$REPO/commits?author=faturrachman.63@smk.belajar.id&since=$TODAY_START_UTC&per_page=100&page=$PAGE" > response.json
              if [[ $? -ne 0 ]]; then
                RETRY_COUNT=$((RETRY_COUNT + 1))
                if [[ $RETRY_COUNT -gt 3 ]]; then
                  echo "Error: Failed to fetch commits for $REPO after 3 retries"
                  exit 1
                fi
                echo "Retrying commit fetch for $REPO ($RETRY_COUNT/3)..."
                sleep 5
                continue
              fi
              PAGE_COMMITS=$(jq length response.json)
              COMMITS=$((COMMITS + PAGE_COMMITS))
              LINK=$(grep -i '^link:' headers.txt || true)
              rm headers.txt response.json
              if [[ ! "$LINK" =~ "rel=\"next\"" ]]; then
                break
              fi
              PAGE=$((PAGE + 1))
              sleep 2  # Increased sleep for stability
            done
            
            echo "Commits in $REPO: $COMMITS"
            TOTAL_COMMITS=$((TOTAL_COMMITS + COMMITS))
            sleep 2  # Increased sleep for stability
          done
          
          echo "Total commits: $TOTAL_COMMITS"
          echo "TODAY_COMMITS=$TOTAL_COMMITS" >> $GITHUB_ENV

      - name: Update README
        run: |
          # Update the placeholder in the comment line
          if grep -q "<!-- TODAY_COMMITS:" faturrachman-dev/README.md; then
            sed -i "s/<!-- TODAY_COMMITS: [0-9]\+ -->/<!-- TODAY_COMMITS: ${{ env.TODAY_COMMITS }} -->/g" faturrachman-dev/README.md
          else
            echo "<!-- TODAY_COMMITS: ${{ env.TODAY_COMMITS }} -->" >> faturrachman-dev/README.md
            echo "![Today's Commits](https://img.shields.io/badge/Today's%20Commits-${{ env.TODAY_COMMITS }}-blue)" >> faturrachman-dev/README.md
          fi
          # Update the badge line with the new commit count
          if grep -q "Today's%20Commits-[0-9]\+-blue" faturrachman-dev/README.md; then
            sed -i "s/\(Today's%20Commits-\)[0-9]\+\(-blue\)/\1${{ env.TODAY_COMMITS }}\2/" faturrachman-dev/README.md
          fi

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update today's commits"
          repository: faturrachman-dev
